export interface Region {
  id: string;
  name: string;
}

export interface Province extends Region {
  cities: Region[];
}

export const INDONESIA_REGIONS: Province[] = [
  {
    id: "aceh",
    name: "Aceh",
    cities: [
      { id: "kab_aceh_barat", name: "Kab. Aceh Barat" },
      { id: "kab_aceh_barat_daya", name: "Kab. Aceh Barat Daya" },
      { id: "kab_aceh_besar", name: "Kab. Aceh Besar" },
      { id: "kab_aceh_jaya", name: "Kab. Aceh Jaya" },
      { id: "kab_aceh_selatan", name: "Kab. Aceh Selatan" },
      { id: "kab_aceh_singkil", name: "Kab. Aceh Singkil" },
      { id: "kab_aceh_tamiang", name: "Kab. Aceh Tamiang" },
      { id: "kab_aceh_tengah", name: "Kab. Aceh Tengah" },
      { id: "kab_aceh_tenggara", name: "Kab. Aceh Tenggara" },
      { id: "kab_aceh_timur", name: "Kab. Aceh Timur" },
      { id: "kab_aceh_utara", name: "Kab. Aceh Utara" },
      { id: "kab_bener_meriah", name: "Kab. Bener Meriah" },
      { id: "kab_bireuen", name: "Kab. Bireuen" },
      { id: "kab_gayo_lues", name: "Kab. Gayo Lues" },
      { id: "kab_nagan_raya", name: "Kab. Nagan Raya" },
      { id: "kab_pidie", name: "Kab. Pidie" },
      { id: "kab_pidie_jaya", name: "Kab. Pidie Jaya" },
      { id: "kab_simeulue", name: "Kab. Simeulue" },
      { id: "banda_aceh", name: "Banda Aceh" },
      { id: "langsa", name: "Langsa" },
      { id: "lhokseumawe", name: "Lhokseumawe" },
      { id: "sabang", name: "Sabang" },
      { id: "subulussalam", name: "Subulussalam" },
    ],
  },
  {
    id: "sumatera_utara",
    name: "Sumatera Utara",
    cities: [
      { id: "kab_asahan", name: "Kab. Asahan" },
      { id: "kab_batubara", name: "Kab. Batubara" },
      { id: "kab_dairi", name: "Kab. Dairi" },
      { id: "kab_deli_serdang", name: "Kab. Deli Serdang" },
      { id: "kab_humbang_hasundutan", name: "Kab. Humbang Hasundutan" },
      { id: "kab_karo", name: "Kab. Karo" },
      { id: "kab_labuhanbatu", name: "Kab. Labuhanbatu" },
      { id: "kab_labuhanbatu_selatan", name: "Kab. Labuhanbatu Selatan" },
      { id: "kab_labuhanbatu_utara", name: "Kab. Labuhanbatu Utara" },
      { id: "kab_langkat", name: "Kab. Langkat" },
      { id: "kab_mandailing_natal", name: "Kab. Mandailing Natal" },
      { id: "kab_nias", name: "Kab. Nias" },
      { id: "kab_nias_barat", name: "Kab. Nias Barat" },
      { id: "kab_nias_selatan", name: "Kab. Nias Selatan" },
      { id: "kab_nias_utara", name: "Kab. Nias Utara" },
      { id: "kab_padang_lawas", name: "Kab. Padang Lawas" },
      { id: "kab_padang_lawas_utara", name: "Kab. Padang Lawas Utara" },
      { id: "kab_pakpak_bharat", name: "Kab. Pakpak Bharat" },
      { id: "kab_samosir", name: "Kab. Samosir" },
      { id: "kab_serdang_bedagai", name: "Kab. Serdang Bedagai" },
      { id: "kab_simalungun", name: "Kab. Simalungun" },
      { id: "kab_tapanuli_selatan", name: "Kab. Tapanuli Selatan" },
      { id: "kab_tapanuli_tengah", name: "Kab. Tapanuli Tengah" },
      { id: "kab_tapanuli_utara", name: "Kab. Tapanuli Utara" },
      { id: "kab_toba_samosir", name: "Kab. Toba Samosir" },
      { id: "binjai", name: "Binjai" },
      { id: "gunungsitoli", name: "Gunungsitoli" },
      { id: "medan", name: "Medan" },
      { id: "padangsidempuan", name: "Padangsidempuan" },
      { id: "pematangsiantar", name: "Pematangsiantar" },
      { id: "sibolga", name: "Sibolga" },
      { id: "tanjungbalai", name: "Tanjungbalai" },
      { id: "tebing_tinggi", name: "Tebing Tinggi" },
    ],
  },
  {
    id: "sumatera_barat",
    name: "Sumatera Barat",
    cities: [
      { id: "kab_agam", name: "Kab. Agam" },
      { id: "kab_dharmasraya", name: "Kab. Dharmasraya" },
      { id: "kab_kepulauan_mentawai", name: "Kab. Kepulauan Mentawai" },
      { id: "kab_lima_puluh_kota", name: "Kab. Lima Puluh Kota" },
      { id: "kab_padang_pariaman", name: "Kab. Padang Pariaman" },
      { id: "kab_pasaman", name: "Kab. Pasaman" },
      { id: "kab_pasaman_barat", name: "Kab. Pasaman Barat" },
      { id: "kab_pesisir_selatan", name: "Kab. Pesisir Selatan" },
      { id: "kab_sijunjung", name: "Kab. Sijunjung" },
      { id: "kab_solok", name: "Kab. Solok" },
      { id: "kab_solok_selatan", name: "Kab. Solok Selatan" },
      { id: "kab_tanah_datar", name: "Kab. Tanah Datar" },
      { id: "bukittinggi", name: "Bukittinggi" },
      { id: "padang", name: "Padang" },
      { id: "padangpanjang", name: "Padangpanjang" },
      { id: "pariaman", name: "Pariaman" },
      { id: "payakumbuh", name: "Payakumbuh" },
      { id: "sawahlunto", name: "Sawahlunto" },
      { id: "solok", name: "Solok" },
    ],
  },
  {
    id: "riau",
    name: "Riau",
    cities: [
      { id: "kab_bengkalis", name: "Kab. Bengkalis" },
      { id: "kab_indragiri_hilir", name: "Kab. Indragiri Hilir" },
      { id: "kab_indragiri_hulu", name: "Kab. Indragiri Hulu" },
      { id: "kab_kampar", name: "Kab. Kampar" },
      { id: "kab_kepulauan_meranti", name: "Kab. Kepulauan Meranti" },
      { id: "kab_kuantan_singingi", name: "Kab. Kuantan Singingi" },
      { id: "kab_pelalawan", name: "Kab. Pelalawan" },
      { id: "kab_rokan_hilir", name: "Kab. Rokan Hilir" },
      { id: "kab_rokan_hulu", name: "Kab. Rokan Hulu" },
      { id: "kab_siak", name: "Kab. Siak" },
      { id: "dumai", name: "Dumai" },
      { id: "pekanbaru", name: "Pekanbaru" },
    ],
  },
  {
    id: "jambi",
    name: "Jambi",
    cities: [
      { id: "kab_batanghari", name: "Kab. Batanghari" },
      { id: "kab_bungo", name: "Kab. Bungo" },
      { id: "kab_kerinci", name: "Kab. Kerinci" },
      { id: "kab_merangin", name: "Kab. Merangin" },
      { id: "kab_muaro_jambi", name: "Kab. Muaro Jambi" },
      { id: "kab_sarolangun", name: "Kab. Sarolangun" },
      { id: "kab_tanjung_jabung_barat", name: "Kab. Tanjung Jabung Barat" },
      { id: "kab_tanjung_jabung_timur", name: "Kab. Tanjung Jabung Timur" },
      { id: "kab_tebo", name: "Kab. Tebo" },
      { id: "jambi", name: "Jambi" },
      { id: "sungai_penuh", name: "Sungai Penuh" },
    ],
  },
  {
    id: "sumatera_selatan",
    name: "Sumatera Selatan",
    cities: [
      { id: "kab_banyuasin", name: "Kab. Banyuasin" },
      { id: "kab_empat_lawang", name: "Kab. Empat Lawang" },
      { id: "kab_lahat", name: "Kab. Lahat" },
      { id: "kab_muara_enim", name: "Kab. Muara Enim" },
      { id: "kab_musi_banyuasin", name: "Kab. Musi Banyuasin" },
      { id: "kab_musi_rawas", name: "Kab. Musi Rawas" },
      { id: "kab_musi_rawas_utara", name: "Kab. Musi Rawas Utara" },
      { id: "kab_ogan_ilir", name: "Kab. Ogan Ilir" },
      { id: "kab_ogan_komering_ilir", name: "Kab. Ogan Komering Ilir" },
      { id: "kab_ogan_komering_ulu", name: "Kab. Ogan Komering Ulu" },
      { id: "kab_ogan_komering_ulu_selatan", name: "Kab. Ogan Komering Ulu Selatan" },
      { id: "kab_ogan_komering_ulu_timur", name: "Kab. Ogan Komering Ulu Timur" },
      { id: "kab_penukal_abab_lematang_ilir", name: "Kab. Penukal Abab Lematang Ilir" },
      { id: "lubuklinggau", name: "Lubuklinggau" },
      { id: "pagar_alam", name: "Pagar Alam" },
      { id: "palembang", name: "Palembang" },
      { id: "prabumulih", name: "Prabumulih" },
    ],
  },
  {
    id: "bengkulu",
    name: "Bengkulu",
    cities: [
      { id: "kab_bengkulu_selatan", name: "Kab. Bengkulu Selatan" },
      { id: "kab_bengkulu_tengah", name: "Kab. Bengkulu Tengah" },
      { id: "kab_bengkulu_utara", name: "Kab. Bengkulu Utara" },
      { id: "kab_kaur", name: "Kab. Kaur" },
      { id: "kab_kepahiang", name: "Kab. Kepahiang" },
      { id: "kab_lebong", name: "Kab. Lebong" },
      { id: "kab_mukomuko", name: "Kab. Mukomuko" },
      { id: "kab_rejang_lebong", name: "Kab. Rejang Lebong" },
      { id: "kab_seluma", name: "Kab. Seluma" },
      { id: "bengkulu", name: "Bengkulu" },
    ],
  },
  {
    id: "lampung",
    name: "Lampung",
    cities: [
      { id: "kab_lampung_barat", name: "Kab. Lampung Barat" },
      { id: "kab_lampung_selatan", name: "Kab. Lampung Selatan" },
      { id: "kab_lampung_tengah", name: "Kab. Lampung Tengah" },
      { id: "kab_lampung_timur", name: "Kab. Lampung Timur" },
      { id: "kab_lampung_utara", name: "Kab. Lampung Utara" },
      { id: "kab_mesuji", name: "Kab. Mesuji" },
      { id: "kab_pesawaran", name: "Kab. Pesawaran" },
      { id: "kab_pesisir_barat", name: "Kab. Pesisir Barat" },
      { id: "kab_pringsewu", name: "Kab. Pringsewu" },
      { id: "kab_tanggamus", name: "Kab. Tanggamus" },
      { id: "kab_tulang_bawang", name: "Kab. Tulang Bawang" },
      { id: "kab_tulang_bawang_barat", name: "Kab. Tulang Bawang Barat" },
      { id: "kab_way_kanan", name: "Kab. Way Kanan" },
      { id: "bandar_lampung", name: "Bandar Lampung" },
      { id: "metro", name: "Metro" },
    ],
  },
  {
    id: "kepulauan_bangka_belitung",
    name: "Kepulauan Bangka Belitung",
    cities: [
      { id: "kab_bangka", name: "Kab. Bangka" },
      { id: "kab_bangka_barat", name: "Kab. Bangka Barat" },
      { id: "kab_bangka_selatan", name: "Kab. Bangka Selatan" },
      { id: "kab_bangka_tengah", name: "Kab. Bangka Tengah" },
      { id: "kab_belitung", name: "Kab. Belitung" },
      { id: "kab_belitung_timur", name: "Kab. Belitung Timur" },
      { id: "pangkal_pinang", name: "Pangkal Pinang" },
    ],
  },
  {
    id: "kepulauan_riau",
    name: "Kepulauan Riau",
    cities: [
      { id: "kab_bintan", name: "Kab. Bintan" },
      { id: "kab_karimun", name: "Kab. Karimun" },
      { id: "kab_kepulauan_anambas", name: "Kab. Kepulauan Anambas" },
      { id: "kab_lingga", name: "Kab. Lingga" },
      { id: "kab_natuna", name: "Kab. Natuna" },
      { id: "batam", name: "Batam" },
      { id: "tanjung_pinang", name: "Tanjung Pinang" },
    ],
  },
  {
    id: "dki_jakarta",
    name: "DKI Jakarta",
    cities: [
      { id: "kep_seribu", name: "Kepulauan Seribu" },
      { id: "jakarta_barat", name: "Jakarta Barat" },
      { id: "jakarta_pusat", name: "Jakarta Pusat" },
      { id: "jakarta_selatan", name: "Jakarta Selatan" },
      { id: "jakarta_timur", name: "Jakarta Timur" },
      { id: "jakarta_utara", name: "Jakarta Utara" },
    ],
  },
  {
    id: "jawa_barat",
    name: "Jawa Barat",
    cities: [
      { id: "kab_bandung", name: "Kab. Bandung" },
      { id: "kab_bandung_barat", name: "Kab. Bandung Barat" },
      { id: "kab_bekasi", name: "Kab. Bekasi" },
      { id: "kab_bogor", name: "Kab. Bogor" },
      { id: "kab_ciamis", name: "Kab. Ciamis" },
      { id: "kab_cianjur", name: "Kab. Cianjur" },
      { id: "kab_cirebon", name: "Kab. Cirebon" },
      { id: "kab_garut", name: "Kab. Garut" },
      { id: "kab_indramayu", name: "Kab. Indramayu" },
      { id: "kab_karawang", name: "Kab. Karawang" },
      { id: "kab_kuningan", name: "Kab. Kuningan" },
      { id: "kab_majalengka", name: "Kab. Majalengka" },
      { id: "kab_pangandaran", name: "Kab. Pangandaran" },
      { id: "kab_purwakarta", name: "Kab. Purwakarta" },
      { id: "kab_subang", name: "Kab. Subang" },
      { id: "kab_sukabumi", name: "Kab. Sukabumi" },
      { id: "kab_sumedang", name: "Kab. Sumedang" },
      { id: "kab_tasikmalaya", name: "Kab. Tasikmalaya" },
      { id: "bandung", name: "Bandung" },
      { id: "banjar", name: "Banjar" },
      { id: "bekasi", name: "Bekasi" },
      { id: "bogor", name: "Bogor" },
      { id: "cimahi", name: "Cimahi" },
      { id: "cirebon", name: "Cirebon" },
      { id: "depok", name: "Depok" },
      { id: "sukabumi", name: "Sukabumi" },
      { id: "tasikmalaya", name: "Tasikmalaya" },
    ],
  },
  {
    id: "jawa_tengah",
    name: "Jawa Tengah",
    cities: [
      { id: "kab_banjarnegara", name: "Kab. Banjarnegara" },
      { id: "kab_banyumas", name: "Kab. Banyumas" },
      { id: "kab_batang", name: "Kab. Batang" },
      { id: "kab_blora", name: "Kab. Blora" },
      { id: "kab_boyolali", name: "Kab. Boyolali" },
      { id: "kab_brebes", name: "Kab. Brebes" },
      { id: "kab_cilacap", name: "Kab. Cilacap" },
      { id: "kab_demak", name: "Kab. Demak" },
      { id: "kab_grobogan", name: "Kab. Grobogan" },
      { id: "kab_jepara", name: "Kab. Jepara" },
      { id: "kab_karanganyar", name: "Kab. Karanganyar" },
      { id: "kab_kebumen", name: "Kab. Kebumen" },
      { id: "kab_kendal", name: "Kab. Kendal" },
      { id: "kab_klaten", name: "Kab. Klaten" },
      { id: "kab_kudus", name: "Kab. Kudus" },
      { id: "kab_magelang", name: "Kab. Magelang" },
      { id: "kab_pati", name: "Kab. Pati" },
      { id: "kab_pekalongan", name: "Kab. Pekalongan" },
      { id: "kab_pemalang", name: "Kab. Pemalang" },
      { id: "kab_purbalingga", name: "Kab. Purbalingga" },
      { id: "kab_purworejo", name: "Kab. Purworejo" },
      { id: "kab_rembang", name: "Kab. Rembang" },
      { id: "kab_semarang", name: "Kab. Semarang" },
      { id: "kab_sragen", name: "Kab. Sragen" },
      { id: "kab_sukoharjo", name: "Kab. Sukoharjo" },
      { id: "kab_tegal", name: "Kab. Tegal" },
      { id: "kab_temanggung", name: "Kab. Temanggung" },
      { id: "kab_wonogiri", name: "Kab. Wonogiri" },
      { id: "kab_wonosobo", name: "Kab. Wonosobo" },
      { id: "magelang", name: "Magelang" },
      { id: "pekalongan", name: "Pekalongan" },
      { id: "salatiga", name: "Salatiga" },
      { id: "semarang", name: "Semarang" },
      { id: "surakarta", name: "Surakarta" },
      { id: "tegal", name: "Tegal" },
    ],
  },
  {
    id: "di_yogyakarta",
    name: "DI Yogyakarta",
    cities: [
      { id: "kab_bantul", name: "Kab. Bantul" },
      { id: "kab_gunungkidul", name: "Kab. Gunungkidul" },
      { id: "kab_kulon_progo", name: "Kab. Kulon Progo" },
      { id: "kab_sleman", name: "Kab. Sleman" },
      { id: "yogyakarta", name: "Yogyakarta" },
    ],
  },
  {
    id: "jawa_timur",
    name: "Jawa Timur",
    cities: [
      { id: "kab_bangkalan", name: "Kab. Bangkalan" },
      { id: "kab_banyuwangi", name: "Kab. Banyuwangi" },
      { id: "kab_blitar", name: "Kab. Blitar" },
      { id: "kab_bojonegoro", name: "Kab. Bojonegoro" },
      { id: "kab_bondowoso", name: "Kab. Bondowoso" },
      { id: "kab_gresik", name: "Kab. Gresik" },
      { id: "kab_jember", name: "Kab. Jember" },
      { id: "kab_jombang", name: "Kab. Jombang" },
      { id: "kab_kediri", name: "Kab. Kediri" },
      { id: "kab_lamongan", name: "Kab. Lamongan" },
      { id: "kab_lumajang", name: "Kab. Lumajang" },
      { id: "kab_madiun", name: "Kab. Madiun" },
      { id: "kab_magetan", name: "Kab. Magetan" },
      { id: "kab_malang", name: "Kab. Malang" },
      { id: "kab_mojokerto", name: "Kab. Mojokerto" },
      { id: "kab_nganjuk", name: "Kab. Nganjuk" },
      { id: "kab_ngawi", name: "Kab. Ngawi" },
      { id: "kab_pacitan", name: "Kab. Pacitan" },
      { id: "kab_pamekasan", name: "Kab. Pamekasan" },
      { id: "kab_pasuruan", name: "Kab. Pasuruan" },
      { id: "kab_ponorogo", name: "Kab. Ponorogo" },
      { id: "kab_probolinggo", name: "Kab. Probolinggo" },
      { id: "kab_sampang", name: "Kab. Sampang" },
      { id: "kab_sidoarjo", name: "Kab. Sidoarjo" },
      { id: "kab_situbondo", name: "Kab. Situbondo" },
      { id: "kab_sumenep", name: "Kab. Sumenep" },
      { id: "kab_trenggalek", name: "Kab. Trenggalek" },
      { id: "kab_tuban", name: "Kab. Tuban" },
      { id: "kab_tulungagung", name: "Kab. Tulungagung" },
      { id: "batu", name: "Batu" },
      { id: "blitar", name: "Blitar" },
      { id: "kediri", name: "Kediri" },
      { id: "madiun", name: "Madiun" },
      { id: "malang", name: "Malang" },
      { id: "mojokerto", name: "Mojokerto" },
      { id: "pasuruan", name: "Pasuruan" },
      { id: "probolinggo", name: "Probolinggo" },
      { id: "surabaya", name: "Surabaya" },
    ],
  },
  {
    id: "banten",
    name: "Banten",
    cities: [
      { id: "kab_lebak", name: "Kab. Lebak" },
      { id: "kab_pandeglang", name: "Kab. Pandeglang" },
      { id: "kab_serang", name: "Kab. Serang" },
      { id: "kab_tangerang", name: "Kab. Tangerang" },
      { id: "cilegon", name: "Cilegon" },
      { id: "serang", name: "Serang" },
      { id: "tangerang", name: "Tangerang" },
      { id: "tangerang_selatan", name: "Tangerang Selatan" },
    ],
  },
  {
    id: "bali",
    name: "Bali",
    cities: [
      { id: "kab_badung", name: "Kab. Badung" },
      { id: "kab_bangli", name: "Kab. Bangli" },
      { id: "kab_buleleng", name: "Kab. Buleleng" },
      { id: "kab_gianyar", name: "Kab. Gianyar" },
      { id: "kab_jembrana", name: "Kab. Jembrana" },
      { id: "kab_karangasem", name: "Kab. Karangasem" },
      { id: "kab_klungkung", name: "Kab. Klungkung" },
      { id: "kab_tabanan", name: "Kab. Tabanan" },
      { id: "denpasar", name: "Denpasar" },
    ],
  },
  {
    id: "nusa_tenggara_barat",
    name: "Nusa Tenggara Barat",
    cities: [
      { id: "kab_bima", name: "Kab. Bima" },
      { id: "kab_dompu", name: "Kab. Dompu" },
      { id: "kab_lombok_barat", name: "Kab. Lombok Barat" },
      { id: "kab_lombok_tengah", name: "Kab. Lombok Tengah" },
      { id: "kab_lombok_timur", name: "Kab. Lombok Timur" },
      { id: "kab_lombok_utara", name: "Kab. Lombok Utara" },
      { id: "kab_sumbawa", name: "Kab. Sumbawa" },
      { id: "kab_sumbawa_barat", name: "Kab. Sumbawa Barat" },
      { id: "bima", name: "Bima" },
      { id: "mataram", name: "Mataram" },
    ],
  },
  {
    id: "nusa_tenggara_timur",
    name: "Nusa Tenggara Timur",
    cities: [
      { id: "kab_alor", name: "Kab. Alor" },
      { id: "kab_belu", name: "Kab. Belu" },
      { id: "kab_ende", name: "Kab. Ende" },
      { id: "kab_flores_timur", name: "Kab. Flores Timur" },
      { id: "kab_kupang", name: "Kab. Kupang" },
      { id: "kab_lembata", name: "Kab. Lembata" },
      { id: "kab_malaka", name: "Kab. Malaka" },
      { id: "kab_manggarai", name: "Kab. Manggarai" },
      { id: "kab_manggarai_barat", name: "Kab. Manggarai Barat" },
      { id: "kab_manggarai_timur", name: "Kab. Manggarai Timur" },
      { id: "kab_nagekeo", name: "Kab. Nagekeo" },
      { id: "kab_ngada", name: "Kab. Ngada" },
      { id: "kab_rote_ndao", name: "Kab. Rote Ndao" },
      { id: "kab_sabu_raijua", name: "Kab. Sabu Raijua" },
      { id: "kab_sikka", name: "Kab. Sikka" },
      { id: "kab_sumba_barat", name: "Kab. Sumba Barat" },
      { id: "kab_sumba_barat_daya", name: "Kab. Sumba Barat Daya" },
      { id: "kab_sumba_tengah", name: "Kab. Sumba Tengah" },
      { id: "kab_sumba_timur", name: "Kab. Sumba Timur" },
      { id: "kab_timor_tengah_selatan", name: "Kab. Timor Tengah Selatan" },
      { id: "kab_timor_tengah_utara", name: "Kab. Timor Tengah Utara" },
      { id: "kupang", name: "Kupang" },
    ],
  },
  {
    id: "kalimantan_barat",
    name: "Kalimantan Barat",
    cities: [
      { id: "kab_bengkayang", name: "Kab. Bengkayang" },
      { id: "kab_kapuas_hulu", name: "Kab. Kapuas Hulu" },
      { id: "kab_kayong_utara", name: "Kab. Kayong Utara" },
      { id: "kab_ketapang", name: "Kab. Ketapang" },
      { id: "kab_kubu_raya", name: "Kab. Kubu Raya" },
      { id: "kab_landak", name: "Kab. Landak" },
      { id: "kab_melawi", name: "Kab. Melawi" },
      { id: "kab_mempawah", name: "Kab. Mempawah" },
      { id: "kab_sambas", name: "Kab. Sambas" },
      { id: "kab_sanggau", name: "Kab. Sanggau" },
      { id: "kab_sekadau", name: "Kab. Sekadau" },
      { id: "kab_sintang", name: "Kab. Sintang" },
      { id: "pontianak", name: "Pontianak" },
      { id: "singkawang", name: "Singkawang" },
    ],
  },
  {
    id: "kalimantan_tengah",
    name: "Kalimantan Tengah",
    cities: [
      { id: "kab_barito_selatan", name: "Kab. Barito Selatan" },
      { id: "kab_barito_timur", name: "Kab. Barito Timur" },
      { id: "kab_barito_utara", name: "Kab. Barito Utara" },
      { id: "kab_gunung_mas", name: "Kab. Gunung Mas" },
      { id: "kab_kapuas", name: "Kab. Kapuas" },
      { id: "kab_katingan", name: "Kab. Katingan" },
      { id: "kab_kotawaringin_barat", name: "Kab. Kotawaringin Barat" },
      { id: "kab_kotawaringin_timur", name: "Kab. Kotawaringin Timur" },
      { id: "kab_lamandau", name: "Kab. Lamandau" },
      { id: "kab_murung_raya", name: "Kab. Murung Raya" },
      { id: "kab_pulang_pisau", name: "Kab. Pulang Pisau" },
      { id: "kab_seruyan", name: "Kab. Seruyan" },
      { id: "kab_sukamara", name: "Kab. Sukamara" },
      { id: "palangka_raya", name: "Palangka Raya" },
    ],
  },
  {
    id: "kalimantan_selatan",
    name: "Kalimantan Selatan",
    cities: [
      { id: "kab_balangan", name: "Kab. Balangan" },
      { id: "kab_banjar", name: "Kab. Banjar" },
      { id: "kab_barito_kuala", name: "Kab. Barito Kuala" },
      { id: "kab_hulu_sungai_selatan", name: "Kab. Hulu Sungai Selatan" },
      { id: "kab_hulu_sungai_tengah", name: "Kab. Hulu Sungai Tengah" },
      { id: "kab_hulu_sungai_utara", name: "Kab. Hulu Sungai Utara" },
      { id: "kab_kotabaru", name: "Kab. Kotabaru" },
      { id: "kab_tabalong", name: "Kab. Tabalong" },
      { id: "kab_tanah_bumbu", name: "Kab. Tanah Bumbu" },
      { id: "kab_tanah_laut", name: "Kab. Tanah Laut" },
      { id: "kab_tapin", name: "Kab. Tapin" },
      { id: "banjarbaru", name: "Banjarbaru" },
      { id: "banjarmasin", name: "Banjarmasin" },
    ],
  },
  {
    id: "kalimantan_timur",
    name: "Kalimantan Timur",
    cities: [
      { id: "kab_berau", name: "Kab. Berau" },
      { id: "kab_kutai_barat", name: "Kab. Kutai Barat" },
      { id: "kab_kutai_kartanegara", name: "Kab. Kutai Kartanegara" },
      { id: "kab_kutai_timur", name: "Kab. Kutai Timur" },
      { id: "kab_mahakam_ulu", name: "Kab. Mahakam Ulu" },
      { id: "kab_paser", name: "Kab. Paser" },
      { id: "kab_penajam_paser_utara", name: "Kab. Penajam Paser Utara" },
      { id: "balikpapan", name: "Balikpapan" },
      { id: "bontang", name: "Bontang" },
      { id: "samarinda", name: "Samarinda" },
    ],
  },
  {
    id: "kalimantan_utara",
    name: "Kalimantan Utara",
    cities: [
      { id: "kab_bulungan", name: "Kab. Bulungan" },
      { id: "kab_malinau", name: "Kab. Malinau" },
      { id: "kab_nunukan", name: "Kab. Nunukan" },
      { id: "kab_tana_tidung", name: "Kab. Tana Tidung" },
      { id: "tarakan", name: "Tarakan" },
    ],
  },
  {
    id: "sulawesi_utara",
    name: "Sulawesi Utara",
    cities: [
      { id: "kab_bolaang_mongondow", name: "Kab. Bolaang Mongondow" },
      { id: "kab_bolaang_mongondow_selatan", name: "Kab. Bolaang Mongondow Selatan" },
      { id: "kab_bolaang_mongondow_timur", name: "Kab. Bolaang Mongondow Timur" },
      { id: "kab_bolaang_mongondow_utara", name: "Kab. Bolaang Mongondow Utara" },
      { id: "kab_kepulauan_sangihe", name: "Kab. Kepulauan Sangihe" },
      { id: "kab_kepulauan_siau_tagulandang_biaro", name: "Kab. Kepulauan Siau Tagulandang Biaro" },
      { id: "kab_kepulauan_talaud", name: "Kab. Kepulauan Talaud" },
      { id: "kab_minahasa", name: "Kab. Minahasa" },
      { id: "kab_minahasa_selatan", name: "Kab. Minahasa Selatan" },
      { id: "kab_minahasa_tenggara", name: "Kab. Minahasa Tenggara" },
      { id: "kab_minahasa_utara", name: "Kab. Minahasa Utara" },
      { id: "bitung", name: "Bitung" },
      { id: "kotamobagu", name: "Kotamobagu" },
      { id: "manado", name: "Manado" },
      { id: "tomohon", name: "Tomohon" },
    ],
  },
  {
    id: "sulawesi_tengah",
    name: "Sulawesi Tengah",
    cities: [
      { id: "kab_banggai", name: "Kab. Banggai" },
      { id: "kab_banggai_kepulauan", name: "Kab. Banggai Kepulauan" },
      { id: "kab_banggai_laut", name: "Kab. Banggai Laut" },
      { id: "kab_buol", name: "Kab. Buol" },
      { id: "kab_donggala", name: "Kab. Donggala" },
      { id: "kab_morowali", name: "Kab. Morowali" },
      { id: "kab_morowali_utara", name: "Kab. Morowali Utara" },
      { id: "kab_parigi_moutong", name: "Kab. Parigi Moutong" },
      { id: "kab_poso", name: "Kab. Poso" },
      { id: "kab_sigi", name: "Kab. Sigi" },
      { id: "kab_tojo_una_una", name: "Kab. Tojo Una-Una" },
      { id: "kab_toli_toli", name: "Kab. Toli-Toli" },
      { id: "palu", name: "Palu" },
    ],
  },
  {
    id: "sulawesi_selatan",
    name: "Sulawesi Selatan",
    cities: [
      { id: "kab_bantaeng", name: "Kab. Bantaeng" },
      { id: "kab_barru", name: "Kab. Barru" },
      { id: "kab_bone", name: "Kab. Bone" },
      { id: "kab_bulukumba", name: "Kab. Bulukumba" },
      { id: "kab_enrekang", name: "Kab. Enrekang" },
      { id: "kab_gowa", name: "Kab. Gowa" },
      { id: "kab_jeneponto", name: "Kab. Jeneponto" },
      { id: "kab_kepulauan_selayar", name: "Kab. Kepulauan Selayar" },
      { id: "kab_luwu", name: "Kab. Luwu" },
      { id: "kab_luwu_timur", name: "Kab. Luwu Timur" },
      { id: "kab_luwu_utara", name: "Kab. Luwu Utara" },
      { id: "kab_maros", name: "Kab. Maros" },
      { id: "kab_pangkajene_dan_kepulauan", name: "Kab. Pangkajene dan Kepulauan" },
      { id: "kab_pinrang", name: "Kab. Pinrang" },
      { id: "kab_sidenreng_rappang", name: "Kab. Sidenreng Rappang" },
      { id: "kab_sinjai", name: "Kab. Sinjai" },
      { id: "kab_soppeng", name: "Kab. Soppeng" },
      { id: "kab_takalar", name: "Kab. Takalar" },
      { id: "kab_tana_toraja", name: "Kab. Tana Toraja" },
      { id: "kab_toraja_utara", name: "Kab. Toraja Utara" },
      { id: "kab_wajo", name: "Kab. Wajo" },
      { id: "makassar", name: "Makassar" },
      { id: "palopo", name: "Palopo" },
      { id: "parepare", name: "Parepare" },
    ],
  },
  {
    id: "sulawesi_tenggara",
    name: "Sulawesi Tenggara",
    cities: [
      { id: "kab_bombana", name: "Kab. Bombana" },
      { id: "kab_buton", name: "Kab. Buton" },
      { id: "kab_buton_selatan", name: "Kab. Buton Selatan" },
      { id: "kab_buton_tengah", name: "Kab. Buton Tengah" },
      { id: "kab_buton_utara", name: "Kab. Buton Utara" },
      { id: "kab_kolaka", name: "Kab. Kolaka" },
      { id: "kab_kolaka_timur", name: "Kab. Kolaka Timur" },
      { id: "kab_kolaka_utara", name: "Kab. Kolaka Utara" },
      { id: "kab_konawe", name: "Kab. Konawe" },
      { id: "kab_konawe_kepulauan", name: "Kab. Konawe Kepulauan" },
      { id: "kab_konawe_selatan", name: "Kab. Konawe Selatan" },
      { id: "kab_konawe_utara", name: "Kab. Konawe Utara" },
      { id: "kab_muna", name: "Kab. Muna" },
      { id: "kab_muna_barat", name: "Kab. Muna Barat" },
      { id: "kab_wakatobi", name: "Kab. Wakatobi" },
      { id: "bau_bau", name: "Bau-Bau" },
      { id: "kendari", name: "Kendari" },
    ],
  },
  {
    id: "gorontalo",
    name: "Gorontalo",
    cities: [
      { id: "kab_boalemo", name: "Kab. Boalemo" },
      { id: "kab_bone_bolango", name: "Kab. Bone Bolango" },
      { id: "kab_gorontalo", name: "Kab. Gorontalo" },
      { id: "kab_gorontalo_utara", name: "Kab. Gorontalo Utara" },
      { id: "kab_pohuwato", name: "Kab. Pohuwato" },
      { id: "gorontalo", name: "Gorontalo" },
    ],
  },
  {
    id: "sulawesi_barat",
    name: "Sulawesi Barat",
    cities: [
      { id: "kab_majene", name: "Kab. Majene" },
      { id: "kab_mamasa", name: "Kab. Mamasa" },
      { id: "kab_mamuju", name: "Kab. Mamuju" },
      { id: "kab_mamuju_tengah", name: "Kab. Mamuju Tengah" },
      { id: "kab_mamuju_utara", name: "Kab. Mamuju Utara" },
      { id: "kab_polewali_mandar", name: "Kab. Polewali Mandar" },
      { id: "mamuju", name: "Mamuju" },
    ],
  },
  {
    id: "maluku",
    name: "Maluku",
    cities: [
      { id: "kab_buru", name: "Kab. Buru" },
      { id: "kab_buru_selatan", name: "Kab. Buru Selatan" },
      { id: "kab_kepulauan_aru", name: "Kab. Kepulauan Aru" },
      { id: "kab_maluku_barat_daya", name: "Kab. Maluku Barat Daya" },
      { id: "kab_maluku_tengah", name: "Kab. Maluku Tengah" },
      { id: "kab_maluku_tenggara", name: "Kab. Maluku Tenggara" },
      { id: "kab_maluku_tenggara_barat", name: "Kab. Maluku Tenggara Barat" },
      { id: "kab_seram_bagian_barat", name: "Kab. Seram Bagian Barat" },
      { id: "kab_seram_bagian_timur", name: "Kab. Seram Bagian Timur" },
      { id: "ambon", name: "Ambon" },
      { id: "tual", name: "Tual" },
    ],
  },
  {
    id: "maluku_utara",
    name: "Maluku Utara",
    cities: [
      { id: "kab_halmahera_barat", name: "Kab. Halmahera Barat" },
      { id: "kab_halmahera_selatan", name: "Kab. Halmahera Selatan" },
      { id: "kab_halmahera_tengah", name: "Kab. Halmahera Tengah" },
      { id: "kab_halmahera_timur", name: "Kab. Halmahera Timur" },
      { id: "kab_halmahera_utara", name: "Kab. Halmahera Utara" },
      { id: "kab_kepulauan_sula", name: "Kab. Kepulauan Sula" },
      { id: "kab_pulau_morotai", name: "Kab. Pulau Morotai" },
      { id: "kab_pulau_taliabu", name: "Kab. Pulau Taliabu" },
      { id: "ternate", name: "Ternate" },
      { id: "tidore_kepulauan", name: "Tidore Kepulauan" },
    ],
  },
  {
    id: "papua_barat",
    name: "Papua Barat",
    cities: [
      { id: "kab_fakfak", name: "Kab. Fakfak" },
      { id: "kab_kaimana", name: "Kab. Kaimana" },
      { id: "kab_manokwari", name: "Kab. Manokwari" },
      { id: "kab_manokwari_selatan", name: "Kab. Manokwari Selatan" },
      { id: "kab_maybrat", name: "Kab. Maybrat" },
      { id: "kab_pegunungan_arfak", name: "Kab. Pegunungan Arfak" },
      { id: "kab_raja_ampat", name: "Kab. Raja Ampat" },
      { id: "kab_sorong", name: "Kab. Sorong" },
      { id: "kab_sorong_selatan", name: "Kab. Sorong Selatan" },
      { id: "kab_tambrauw", name: "Kab. Tambrauw" },
      { id: "kab_teluk_bintuni", name: "Kab. Teluk Bintuni" },
      { id: "kab_teluk_wondama", name: "Kab. Teluk Wondama" },
    ],
  },
  {
    id: "papua",
    name: "Papua",
    cities: [
      { id: "kab_asmat", name: "Kab. Asmat" },
      { id: "kab_biak_numfor", name: "Kab. Biak Numfor" },
      { id: "kab_boven_digoel", name: "Kab. Boven Digoel" },
      { id: "kab_deiyai", name: "Kab. Deiyai" },
      { id: "kab_dogiyai", name: "Kab. Dogiyai" },
      { id: "kab_intan_jaya", name: "Kab. Intan Jaya" },
      { id: "kab_jayapura", name: "Kab. Jayapura" },
      { id: "kab_jayawijaya", name: "Kab. Jayawijaya" },
      { id: "kab_keerom", name: "Kab. Keerom" },
      { id: "kab_kepulauan_yapen", name: "Kab. Kepulauan Yapen" },
      { id: "kab_lanny_jaya", name: "Kab. Lanny Jaya" },
      { id: "kab_mamberamo_raya", name: "Kab. Mamberamo Raya" },
      { id: "kab_mamberamo_tengah", name: "Kab. Mamberamo Tengah" },
      { id: "kab_mappi", name: "Kab. Mappi" },
      { id: "kab_merauke", name: "Kab. Merauke" },
      { id: "kab_mimika", name: "Kab. Mimika" },
      { id: "kab_nabire", name: "Kab. Nabire" },
      { id: "kab_nduga", name: "Kab. Nduga" },
      { id: "kab_paniai", name: "Kab. Paniai" },
      { id: "kab_pegunungan_bintang", name: "Kab. Pegunungan Bintang" },
      { id: "kab_puncak", name: "Kab. Puncak" },
      { id: "kab_puncak_jaya", name: "Kab. Puncak Jaya" },
      { id: "kab_sarmi", name: "Kab. Sarmi" },
      { id: "kab_supiori", name: "Kab. Supiori" },
      { id: "kab_tolikara", name: "Kab. Tolikara" },
      { id: "kab_waropen", name: "Kab. Waropen" },
      { id: "kab_yahukimo", name: "Kab. Yahukimo" },
      { id: "kab_yalimo", name: "Kab. Yalimo" },
      { id: "jayapura", name: "Jayapura" },
    ],
  },
];